### ISSUE TITLE
Attempt to invoke virtual method 'int io.agora.rtc.RtcEngine.setVideoSource(io.agora.rtc.mediaio.IVideoSource)

### ISSUE THREAD

**Issue by softsan** [DreamTeamMobile/Xamarin.Agora.Samples#31] opened 2021-09-15 20:18 UTC
@sbokatuk -  I'm trying to use the Screenshare android sample into my Xamarin.forms app and follows all the code that are written in RoomActivity of your sample but i get following runtime errror and my app is getting crashed:

```
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'int io.agora.rtc.RtcEngine.setVideoSource(io.agora.rtc.mediaio.IVideoSource)' on a null object reference
[AndroidRuntime] 	at io.agora.advancedvideo.externvideosource.ExternalVideoInputManager$ExternalVideoInputThread.prepare(ExternalVideoInputManager.java:230)
[AndroidRuntime] 	at io.agora.advancedvideo.externvideosource.ExternalVideoInputManager$ExternalVideoInputThread.run(ExternalVideoInputManager.java:252)
[] Thread 0x78d188ad50 may have been prematurely finalized
[] * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/utils/mono-threads.c:650, condition `info' not met, function:mono_thread_info_current, 
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24487 (Thread-37), pid 23583
```

So any idea how this happen?

**Comment by alexsorokoletov** [comment] 2021-09-16 03:08
Hi @softsan!
Can you reproduce the problem with this Screenshare sample?
If so, what are the steps and Xamarin.Android and Android OS versions that you use.

**Comment by softsan** [comment] 2021-09-16 16:08
Hi @alexsorokoletov!
Thanks.
Yes it worked in Xamarin.Android sample and i see the RoomActivity itself configured to start screenshare. 
But in my case,  screen share can  start during video call. 
and it does not work in Xamarin.forms for me.

**Comment by alexsorokoletov** [comment] 2021-09-20 16:06
Thanks for the answer. Unfortunately, we don't offer support here for the code that is not a part of the sample or SDK. 
I would suggest to either
- look into how your usage is different from the sample
- or fork the sample, reproduce the problem and come back with a repro so we can actually act and help.

Thank you!

It looks like there is at least 1 more person interested in this (looking at the emojis) so maybe you can cooperate in this.

**Comment by softsan** [comment] 2021-09-24 12:49
@alexsorokoletov  I further investigated the issue and it looks like doesn't work with Xamarin.forms.
I tried it in your xamarin.forms sample: https://github.com/DreamTeamMobile/Xamarin.Agora.Samples/tree/master/FormsWithNativeNugets
copy the binaries of android: `Agora.Api.Component.dll` and `Agora.Api.ExternalVideo.dll `into this sample and also wrote `ExternalVideoInputManager` and `VideoInputServiceConnection` in android side and then try to call BindService method from Main activity and also after `Agora initialization` and `JoinChannel`:

```
public void BindVideoService()
        {
            var intent = new Intent();
            intent.SetClass(this.BaseContext, typeof(ExternalVideoInputService));
            var serviceConnection = new VideoInputServiceConnection(this);
            serviceConnection.ServiceConnected += (s) => _service = s;
            BaseContext.BindService(intent, serviceConnection, Bind.AutoCreate);
        }
```
but it failed with same error:
```
[AndroidRuntime] Process: com.dreamteammobile.formsagora.DT_Samples_Agora_Cross, PID: 26573
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'int io.agora.rtc.RtcEngine.setVideoSource(io.agora.rtc.mediaio.IVideoSource)' on a null object reference
[AndroidRuntime] 	at io.agora.advancedvideo.externvideosource.ExternalVideoInputManager$ExternalVideoInputThread.prepare(ExternalVideoInputManager.java:230)
[AndroidRuntime] 	at io.agora.advancedvideo.externvideosource.ExternalVideoInputManager$ExternalVideoInputThread.run(ExternalVideoInputManager.java:252)
[] Thread 0x79de516d50 may have been prematurely finalized
```

**Comment by softsan** [comment] 2021-09-27 19:15
@alexsorokoletov @sbokatuk Any suggestion/ideas on above? Thanks

**Comment by alexsorokoletov** [comment] 2021-09-27 19:30
Unfortunately, no ideas here.
There is a null reference somewhere in the execution flow when you reproduce it so the best bet is to find it and the reason why it's null.

I will close the issue since it seems to be a custom code (not Xamarin SDK or sample that we provide).

**Closed as completed by alexsorokoletov** 2021-09-27 19:30 UTC
